In [1]:
%%capture
%run 3-tfidf-gensim.ipynb

In [2]:
from sklearn.decomposition import PCA

In [3]:
n_components = 6
# Fit an PCA model
pca = PCA(n_components=n_components)


In [4]:
from scipy import sparse
import numpy as np

# Convert sparse matrix to dense, if necessary
tfidf_matrix_dense = tfidf_matrix.todense() if sparse.issparse(tfidf_matrix) else tfidf_matrix

# Convert to numpy array
tfidf_matrix_array = np.asarray(tfidf_matrix_dense)

In [5]:
# Centering
import numpy as np

mean_tfidf = np.mean(tfidf_matrix_array, axis=0)  # Calculate the mean of each column
centered_tfidf_matrix = tfidf_matrix_array - mean_tfidf

In [6]:
# Fit PCA on the centered dense matrix
principal_components = pca.fit_transform(centered_tfidf_matrix)

principal_components

array([[-0.17429446,  0.03103896,  0.21486303,  0.01135467,  0.07523099,
         0.06916486],
       [-0.35083929,  0.09202308,  0.365166  ,  0.05351269,  0.16939092,
         0.05251914],
       [-0.07695142,  0.0159261 ,  0.05043736,  0.01756237,  0.03774716,
        -0.01876586],
       ...,
       [-0.08662656, -0.00415903,  0.08049806, -0.00862126,  0.01751917,
         0.03548263],
       [-0.07376728,  0.00586906,  0.05972444,  0.02273549,  0.00895427,
         0.02783178],
       [-0.09354149,  0.02385921,  0.05962311, -0.00283022,  0.00909843,
        -0.02321702]])

In [7]:
cumulative_explained_variance = np.cumsum(pca.explained_variance_ratio_)
print("Cumulative Explained Variance:")
print(cumulative_explained_variance)
print(sum(cumulative_explained_variance))

Cumulative Explained Variance:
[0.00591851 0.01081238 0.01528253 0.01923502 0.02286871 0.02626643]
0.10038357384409173


In [8]:
pca.components_

array([[-4.70442070e-03, -4.07112026e-03, -2.11318262e-03, ...,
        -7.52371265e-03,  2.54578293e-04,  3.69694290e-03],
       [ 4.53173157e-06,  7.51318198e-04,  1.13724217e-03, ...,
        -4.41231883e-03,  3.25224683e-03, -1.62350645e-03],
       [-7.00319806e-04,  2.36814667e-03,  1.05735167e-03, ...,
        -9.16253944e-03, -3.98758429e-05,  7.35774078e-04],
       [ 1.35343500e-03,  1.90859396e-04,  1.89453871e-03, ...,
         3.37592331e-03,  1.48062510e-03,  3.13532005e-04],
       [ 4.35811933e-03,  9.19060335e-04, -3.27813910e-04, ...,
         4.79230300e-03, -8.48216627e-03, -4.15309142e-03],
       [ 3.94820103e-04, -1.32213044e-03, -1.33153177e-03, ...,
        -4.94438892e-03, -1.00356766e-02,  5.41800140e-03]])

In [9]:
import numpy as np

loadings = pca.components_

for i, component in enumerate(loadings):
    component_words = [(tfidf_feature_names[j], component[j]) for j in component.argsort()[::-1][:10]]
    print(f"Component {i+1}:")
    for word, loading in component_words:
        print(f"{word}: {loading:.3f}")
    print()

Component 1:
card: 0.253
drive: 0.209
video: 0.147
sale: 0.121
monitor: 0.120
color: 0.120
file: 0.112
mac: 0.112
disk: 0.110
system: 0.109

Component 2:
chip: 0.425
key: 0.333
clipper: 0.306
encryption: 0.271
government: 0.175
system: 0.126
escrow: 0.121
algorithm: 0.111
security: 0.104
public: 0.102

Component 3:
god: 0.470
drive: 0.134
card: 0.130
believe: 0.110
faith: 0.100
problem: 0.082
life: 0.074
video: 0.073
truth: 0.071
color: 0.070

Component 4:
drive: 0.522
ide: 0.195
car: 0.175
hard: 0.171
controller: 0.141
disk: 0.137
sale: 0.129
floppy: 0.105
chip: 0.097
buy: 0.088

Component 5:
card: 0.337
game: 0.250
team: 0.238
god: 0.236
win: 0.189
video: 0.185
hockey: 0.138
chip: 0.137
play: 0.118
color: 0.118

Component 6:
card: 0.353
sale: 0.340
video: 0.179
god: 0.177
chip: 0.133
distribution: 0.108
monitor: 0.107
sell: 0.104
offer: 0.103
price: 0.089



In [11]:
#topics = ["computer", "recreation", "science", "miscellaneous", "politics", "religion"]